AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 40
Style/MultilineBlockChain:
  Enabled: false
Metrics/BlockLength:
  Max: 50
