AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true

MethodLength:
  Max: 30
Style/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 40
Style/MultilineBlockChain:
  Enabled: false
Metrics/BlockLength:
  Max: 50
