assets:
  rubygems.yml: "yegor256/home#assets/rubygems.yml"

release:
  script:
    - "sudo apt-get update"
    - "sudo apt-get install -y --fix-missing libmagic1 libmagic-dev"
    - "sudo bundle install"
    - "rake"
    - "rm -rf *.gem"
    - "sed -i 's/1\\.0\\.snapshot/${tag}/g' pdd.gemspec"
    - "gem build pdd.gemspec"
    - "chmod 0600 ../rubygems.yml"
    - "gem push *.gem --config-file ../rubygems.yml"

