assets:
  rubygems.yml: "yegor256/home#assets/rubygems.yml"
  s3cfg: "yegor256/home#assets/s3cfg"

install: |
  sudo apt-get update
  sudo apt-get install -y --fix-missing libmagic1 libmagic-dev
  sudo gem install pdd

release:
  script: |
    sudo bundle install
    rake
    rm -rf *.gem
    sed -i 's/1\.0\.snapshot/${tag}/g' lib/pdd/version.rb
    gem build pdd.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    pdd --source=$(pwd) --verbose --file=pdd.xml -e=test/** -e=features/** -e=README.md
    s3cmd --no-progress put pdd.xml --config=../s3cfg s3://pdd.teamed.io/pdd.xml
    s3cmd --no-progress put assets/puzzles.xsd --acl-public --config=../s3cfg s3://pdd-xsd.teamed.io/${tag}.xsd
    s3cmd --no-progress put assets/puzzles.xsl --acl-public --config=../s3cfg s3://pdd-xsl.teamed.io/${tag}.xsl
