assets:
  rubygems.yml: "yegor256/home#assets/rubygems.yml"

release:
  script:
    - "rake"
    - "rm -rf *.gem"
    - "sed -i \"s/1\.0\.pre/${tag}/g\" jgd.gemspec"
    - "gem build jgd.gemspec"
    - "chmod 0600 ../rubygems.yml"
    - "gem push *.gem --config-file ../rubygems.yml"

