language: ruby
rvm:
  - 2.0.0
cache: bundler
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libmagic1
      - libmagic-dev
install:
  - travis_retry bundle install
script:
  - rake

